name: Playwright Automated Tests
on:
  push:
    branches: [ master ]
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Obtain test automation project code
      uses: actions/checkout@v3

    - name: Install Node Version 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run e2e tests
      run: npx playwright test

    - name: Publish HTML Execution Report
      uses: actions/upload-artifact@v3
      if: always()
      with: 
        name: playwright-report
        path: playwright-report/
        retention-days: 15